// app/layout.tsx or app/layout.jsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Livio",
  description: "Generated by create next app",
};

// Replace this with your actual client ID
const clientId =
  "632507126049-olsukmqgjf7ko3240fddqeiedpnr23uu.apps.googleusercontent.com";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ height: "100vh", width: "100%" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ height: "100%", width: "100%", margin: 0, padding: 0 }}
      >
        {children}
      </body>
    </html>
  );
}
